In [24]:
import numpy as np

In [25]:
np.__version__

'1.19.2'

In [49]:
array = np.arange (21)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [40]:
array[(array%2==0)]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [41]:
array[(array%3==0)]

array([ 0,  3,  6,  9, 12, 15, 18])