In [1]:
import numpy as np

In [14]:
a = np.arange(30).reshape(5,6, order='F')

In [15]:
print (a)

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [17]:
np.argwhere(a%6==1)

array([[0, 5],
       [1, 0],
       [2, 1],
       [3, 2],
       [4, 3]], dtype=int64)