In [2]:
import numpy as np

In [14]:
x = np.array(range(30))
y = np.array([2,3,5])

In [15]:
with open('multi_array.npz','wb') as f:
    np.savez(f, x, y)

In [16]:
npzfile = np.load('multi_array.npz')
type(npzfile)

numpy.lib.npyio.NpzFile

In [17]:
npzfile.files

['arr_0', 'arr_1']

In [18]:
print(npzfile['arr_0'])
print(npzfile['arr_1'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [19]:
z = np.array([[4,5,6],[1,2,3]])

In [35]:
with open('multi_array.npz','wb') as new:
    np.savez(new, array1=x, array2=y, array3=z)

In [36]:
newnpzfile = np.load('multi_array.npz')
type(newnpzfile)

numpy.lib.npyio.NpzFile

In [37]:
newnpzfile.files

['array1', 'array2', 'array3']

In [40]:
print(newnpzfile['array1'])
print(newnpzfile['array2'])
print(newnpzfile['array3'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[[4 5 6]
 [1 2 3]]
